# Generated by Django 6.0.4 on 2026-05-04 06:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Land', 'Land'), ('Water', 'Water'), ('Utility', 'Utility'), ('Building', 'Building'), ('Facility', 'Facility'), ('Road', 'Road')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('length_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('maintenance_status', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_code', models.CharField(max_length=20, unique=True)),
                ('house_material', models.CharField(choices=[('Concrete', 'Concrete'), ('Wood', 'Wood'), ('Mixed', 'Mixed')], default='Concrete', max_length=20)),
                ('ownership_status', models.CharField(choices=[('Owned', 'Owned'), ('Rented', 'Rented')], default='Owned', max_length=20)),
                ('head_of_family', models.CharField(blank=True, default='', max_length=100)),
                ('number_of_members', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('president', models.CharField(blank=True, default='', max_length=100)),
                ('members', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('programs', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('Health Worker', 'Health Worker'), ('Nurse', 'Nurse'), ('Midwife', 'Midwife'), ('Doctor', 'Doctor'), ('Dentist', 'Dentist')], default='Health Worker', max_length=50)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OtherProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(choices=[('Teacher', 'Teacher'), ('Carpenter', 'Carpenter'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Farmer', 'Farmer'), ('Engineer', 'Engineer'), ('Other', 'Other')], default='Teacher', max_length=50)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_name', models.CharField(default='Cogon', max_length=100)),
                ('municipality', models.CharField(blank=True, default='', max_length=100)),
                ('province', models.CharField(blank=True, default='', max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('vision', models.TextField(blank=True, default='')),
                ('mission', models.TextField(blank=True, default='')),
                ('goals', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Captain', 'Captain'), ('Secretary', 'Secretary'), ('Health Worker', 'Health Worker')], default='Captain', max_length=50)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Barangay User',
                'verbose_name_plural': 'Barangay Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('civil_status', models.CharField(blank=True, choices=[('', 'None'), ('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], default='', max_length=20)),
                ('citizenship', models.CharField(choices=[('Filipino', 'Filipino'), ('Foreigner', 'Foreigner')], default='Filipino', max_length=20)),
                ('livelihood', models.CharField(blank=True, default='', max_length=100)),
                ('house_material', models.CharField(blank=True, default='', max_length=20)),
                ('ownership_status', models.CharField(blank=True, default='', max_length=20)),
                ('disability', models.BooleanField(default=False)),
                ('lgbtq_type', models.CharField(blank=True, choices=[('', 'None'), ('Gay', 'Gay'), ('Lesbian', 'Lesbian'), ('Bisexual', 'Bisexual'), ('Transgender', 'Transgender')], default='', max_length=20)),
                ('is_labor_force', models.BooleanField(default=False)),
                ('is_unemployed', models.BooleanField(default=False)),
                ('is_ofw', models.BooleanField(default=False)),
                ('is_solo_parent', models.BooleanField(default=False)),
                ('is_indigenous', models.BooleanField(default=False)),
                ('is_osc', models.BooleanField(default=False)),
                ('is_osy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.household')),
            ],
        ),
    ]
