# Generated by Django 4.2.30 on 2026-05-10 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BarangayProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("municipality", models.CharField(blank=True, max_length=100)),
                ("province", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("captain", models.CharField(blank=True, max_length=100)),
                ("contact", models.CharField(blank=True, max_length=20)),
                ("vision", models.TextField(blank=True)),
                ("mission", models.TextField(blank=True)),
                ("goals", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Barangay Profile",
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "building_type",
                    models.CharField(
                        choices=[
                            ("Health Facility", "Health Facility"),
                            ("Educational", "Educational"),
                            ("Emergency", "Emergency"),
                            ("Government", "Government"),
                            ("Religious", "Religious"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Operational", "Operational"),
                            ("Under Repair", "Under Repair"),
                            ("Closed", "Closed"),
                        ],
                        default="Operational",
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("Agricultural", "Agricultural"),
                            ("Residential", "Residential"),
                            ("Forest", "Forest"),
                            ("Commercial", "Commercial"),
                            ("Industrial", "Industrial"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "area_ha",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Professional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "profession",
                    models.CharField(
                        choices=[
                            ("Teacher", "Teacher"),
                            ("Carpenter", "Carpenter"),
                            ("Electrician", "Electrician"),
                            ("Plumber", "Plumber"),
                            ("Engineer", "Engineer"),
                            ("Mechanic", "Mechanic"),
                            ("Farmer", "Farmer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="RoadNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "road_type",
                    models.CharField(
                        choices=[
                            ("Concrete", "Concrete"),
                            ("Gravel", "Gravel"),
                            ("Asphalt", "Asphalt"),
                            ("Dirt Road", "Dirt Road"),
                        ],
                        max_length=15,
                    ),
                ),
                ("length_km", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[("Good", "Good"), ("Fair", "Fair"), ("Poor", "Poor")],
                        default="Good",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Utility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "electricity",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Not Available", "Not Available"),
                        ],
                        default="Available",
                        max_length=15,
                    ),
                ),
                (
                    "water_supply",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Not Available", "Not Available"),
                        ],
                        default="Available",
                        max_length=15,
                    ),
                ),
                (
                    "waste_management",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Not Available", "Not Available"),
                        ],
                        default="Available",
                        max_length=15,
                    ),
                ),
                ("toilet_count", models.PositiveIntegerField(default=0)),
                ("bath_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Utilities",
            },
        ),
        migrations.CreateModel(
            name="WaterBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "water_type",
                    models.CharField(
                        choices=[
                            ("River", "River"),
                            ("Creek", "Creek"),
                            ("Lake", "Lake"),
                            ("Spring", "Spring"),
                            ("Dam", "Dam"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name="OtherProfessional",
        ),
        migrations.DeleteModel(
            name="Settings",
        ),
        migrations.AlterModelOptions(
            name="facility",
            options={"verbose_name_plural": "Facilities"},
        ),
        migrations.AlterModelOptions(
            name="medicalstaff",
            options={"verbose_name_plural": "Medical Staff"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RenameField(
            model_name="household",
            old_name="household_code",
            new_name="household_id",
        ),
        migrations.RenameField(
            model_name="medicalstaff",
            old_name="name",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="resident",
            old_name="full_name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="resident",
            old_name="disability",
            new_name="has_disability",
        ),
        migrations.RenameField(
            model_name="resident",
            old_name="is_labor_force",
            new_name="in_labor_force",
        ),
        migrations.RemoveField(
            model_name="facility",
            name="area",
        ),
        migrations.RemoveField(
            model_name="facility",
            name="category",
        ),
        migrations.RemoveField(
            model_name="facility",
            name="description",
        ),
        migrations.RemoveField(
            model_name="facility",
            name="length_km",
        ),
        migrations.RemoveField(
            model_name="facility",
            name="maintenance_status",
        ),
        migrations.RemoveField(
            model_name="facility",
            name="status",
        ),
        migrations.RemoveField(
            model_name="facility",
            name="type",
        ),
        migrations.RemoveField(
            model_name="household",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="household",
            name="head_of_family",
        ),
        migrations.RemoveField(
            model_name="household",
            name="number_of_members",
        ),
        migrations.RemoveField(
            model_name="household",
            name="ownership_status",
        ),
        migrations.RemoveField(
            model_name="medicalstaff",
            name="contact_number",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="age",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="house_material",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="is_osc",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="is_osy",
        ),
        migrations.RemoveField(
            model_name="resident",
            name="ownership_status",
        ),
        migrations.RemoveField(
            model_name="user",
            name="contact_number",
        ),
        migrations.AddField(
            model_name="facility",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("Community", "Community"),
                    ("Security", "Security"),
                    ("Transport", "Transport"),
                    ("Health", "Health"),
                    ("Education", "Education"),
                ],
                default="Community",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="household",
            name="ownership",
            field=models.CharField(
                blank=True,
                choices=[("Owned", "Owned"), ("Rented", "Rented")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="medicalstaff",
            name="contact",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="resident",
            name="last_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resident",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="contact",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
        migrations.AlterField(
            model_name="facility",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="household",
            name="house_material",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Concrete", "Concrete"),
                    ("Wood", "Wood"),
                    ("Mixed", "Mixed"),
                    ("Light Material", "Light Material"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="members",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="institution",
            name="president",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="institution",
            name="programs",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="institution",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="medicalstaff",
            name="position",
            field=models.CharField(
                choices=[
                    ("Doctor", "Doctor"),
                    ("Health Worker", "Health Worker"),
                    ("Nurse", "Nurse"),
                    ("Midwife", "Midwife"),
                    ("Dentist", "Dentist"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="birth_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="resident",
            name="citizenship",
            field=models.CharField(
                choices=[("Filipino", "Filipino"), ("Foreigner", "Foreigner")],
                default="Filipino",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="civil_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Widowed", "Widowed"),
                    ("Separated", "Separated"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="residents",
                to="accounts.household",
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="lgbtq_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("Gay", "Gay"),
                    ("Lesbian", "Lesbian"),
                    ("Bisexual", "Bisexual"),
                    ("Transgender", "Transgender"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="resident",
            name="livelihood",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Farming", "Farming"),
                    ("Teaching", "Teaching"),
                    ("Student", "Student"),
                    ("Construction", "Construction"),
                    ("Small Business", "Small Business"),
                    ("Retail", "Retail"),
                    ("Healthcare", "Healthcare"),
                    ("Government", "Government"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Captain", "Barangay Captain"),
                    ("Secretary", "Barangay Secretary"),
                    ("Health Worker", "Health Worker"),
                    ("Treasurer", "Barangay Treasurer"),
                    ("Councilor", "Barangay Councilor"),
                ],
                max_length=20,
            ),
        ),
    ]
