# Generated by Django 4.2.30 on 2026-05-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_barangayprofile_building_landbody_professional_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="head",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="household",
            name="household_id",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="resident",
            name="birth_date",
            field=models.DateField(default="2000-01-01"),
        ),
    ]
