# Generated by Django 4.2.30 on 2026-05-17 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_restore_deleted_module_tables"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="barangayprofile",
            options={"verbose_name_plural": "Barangay Profiles"},
        ),
        migrations.AlterModelOptions(
            name="medicalstaff",
            options={},
        ),
        migrations.RenameField(
            model_name="medicalstaff",
            old_name="full_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="professional",
            old_name="full_name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="building",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facility",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="institution",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landbody",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medicalstaff",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professional",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roadnetwork",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="waterbody",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="barangayprofile",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="household",
            name="house_material",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Concrete", "Concrete"),
                    ("Wood", "Wood"),
                    ("Mixed", "Mixed"),
                    ("Light Materials", "Light Materials"),
                    ("Semi-Concrete", "Semi-Concrete"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="household",
            name="ownership",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Owned", "Owned"),
                    ("Rented", "Rented"),
                    ("Shared", "Shared"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Captain", "Captain"),
                    ("Secretary", "Secretary"),
                    ("Health Worker", "Health Worker"),
                    ("Treasurer", "Treasurer"),
                    ("Councilor", "Councilor"),
                ],
                max_length=50,
            ),
        ),
    ]
