# Generated by Django 4.2.30 on 2026-05-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_barangayprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
