# Generated by Django 4.2.30 on 2026-05-20 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_resident_middle_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Institution",
        ),
        migrations.AddField(
            model_name="medicalstaff",
            name="resident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medical_staff",
                to="accounts.resident",
            ),
        ),
        migrations.AddField(
            model_name="professional",
            name="resident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professionals",
                to="accounts.resident",
            ),
        ),
    ]
